maxSurge: 50%
maxUnavailable: 50%
replicaCount: 2
image:
  repository: strangehoon2/seniors
  pullPolicy: Always
  tag: "sha-9885bac"
service:
  type: NodePort
maxReplicas: 10
minReplicas: 2
targetCPUUtilizationPercentage: 50
