maxSurge: 50%
maxUnavailable: 50%
replicaCount: 2
image:
  repository: strangehoon2/seniors
  pullPolicy: Always
  tag: "sha-731dfbf"
service:
  type: NodePort
maxReplicas: 5
minReplicas: 2
targetCPUUtilizationPercentage: 70
